name: roozterfaceapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=3.2.0 <4.0.0' # Actualizado a un rango moderno

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- DEPENDENCIAS DE FIREBASE ACTUALIZADAS Y ALINEADAS ---
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  cloud_functions: ^4.6.8
  
  # Dependencias de UI y Utilidades
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.20.2 # La última versión estable
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  in_app_purchase: ^3.1.13
  graphview: ^1.2.0
  fl_chart: ^0.67.0
  cupertino_icons: ^1.0.6
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/